GAME_WIDTH = 1280
GAME_HEIGHT = 720

CLIENT_VERSION = "v0.0.2"

PUBLIC_IP = "75.119.187.81"

# ⚙️ Server Settings (FastAPI)
SERVER_HOST = f"{PUBLIC_IP}"  # change to your server's LAN IP
SERVER_PORT = 8000
SERVER_URL = f"http://{SERVER_HOST}:{SERVER_PORT}"
